name: Daily Download at 1PM MYT

on:
  schedule:
    - cron: '0 5 * * *'   # 05:00 UTC = 13:00 MYT
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-download:
    runs-on: ubuntu-latest
    env:
      WEBSITE_USERNAME: ${{ secrets.WEBSITE_USERNAME }}
      WEBSITE_PASSWORD: ${{ secrets.WEBSITE_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run download script
        run: python download.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.0.3
        with:
          name: downloads-zip
          path: downloads/*.zip
          if-no-files-found: warn
